import React from "react";

const ConstrainedDecodingSection: React.FC = () => {
	return (
		<section className="py-16 bg-gray-50">
			<div className="container mx-auto">
				<h2 className="text-3xl font-bold text-gray-900 mb-8">
					Constrained Decoding
				</h2>

				<div className="prose prose-lg max-w-none">
					<p className="text-gray-700 leading-relaxed mb-6">
						We explore a new defense direction of constrained decoding for
						secure code generation. Given a set of constraints, constrained
						decoding needs to generate code that satisfies all the constraints.
						In our paper, we specify security constraints for code generated by
						prompts in CodeGuard+. To specify the security constraints, we use
						knowledge about common secure coding practices and the corresponding
						CWE type that might be triggered by the prompt. For example, to
						avoid out-of-bound write, we need the generated code to do the array
						index bound check; to process untrusted user input, the generated
						code should perform input validation.
					</p>
				</div>

				<div className="mt-8 grid md:grid-cols-2 gap-8">
					<div className="bg-white rounded-lg p-6 border border-gray-200">
						<h3 className="text-lg font-semibold text-gray-900 mb-4">
							Benefits
						</h3>
						<ul className="space-y-3 text-gray-700">
							<li className="flex items-start">
								<span className="text-green-600 mr-2">✓</span>
								More effective than prefix tuning for security
							</li>
							<li className="flex items-start">
								<span className="text-green-600 mr-2">✓</span>
								No specialized training dataset required
							</li>
							<li className="flex items-start">
								<span className="text-green-600 mr-2">✓</span>
								Strong performance across multiple Code LLMs
							</li>
							<li className="flex items-start">
								<span className="text-green-600 mr-2">✓</span>
								Outperforms GPT-4 with constrained decoding
							</li>
						</ul>
					</div>

					<div className="bg-white rounded-lg p-6 border border-gray-200">
						<h3 className="text-lg font-semibold text-gray-900 mb-4">
							Supported Models
						</h3>
						<p className="text-gray-700 mb-4">
							Our constrained decoding technique improves secure-pass@1 across
							models ranging from 2.7B to 34B parameters:
						</p>
						<div className="flex flex-wrap gap-2">
							{[
								"CodeGen",
								"StarCoder",
								"CodeT5+",
								"CodeLlama",
								"GPT-4",
								"Claude",
							].map((model) => (
								<span
									key={model}
									className="px-3 py-1 bg-blue-100 text-blue-800 text-sm rounded-full"
								>
									{model}
								</span>
							))}
						</div>
					</div>
				</div>
			</div>
		</section>
	);
};

export default ConstrainedDecodingSection;

